#!/bin/bash

# Takes a single argument, decodes it, and echoes the result to STDOUT
#
# Usage: base64_decode "dGVzdAo=" # echoes "test"
base64_decode() {
  base64 -d <<< "$1"
}

# Save the SSH key if it's in the environment
if [[ -n "${BUILDKITE_ID_RSA_BASE64:-}" ]]; then
  mkdir -p "$HOME/.ssh"
  rm -f "$HOME/.ssh/id_rsa"
  base64_decode "$BUILDKITE_ID_RSA_BASE64" > "$HOME/.ssh/id_rsa"
  chmod 400 "$HOME/.ssh/id_rsa"
  export BUILDKITE_ID_RSA_BASE64=""

  echo "Created ~/.ssh/id_rsa"
else
  echo "No SSH key found in environment"
fi
